// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6uCCqh2uJWIBh1m8BKsvSdvT7gyKFRqY',
    appId: '1:932316550763:web:31f38e478808dbb0ee032e',
    messagingSenderId: '932316550763',
    projectId: 'barn-d496f',
    authDomain: 'barn-d496f.firebaseapp.com',
    storageBucket: 'barn-d496f.firebasestorage.app',
    measurementId: 'G-08BES47TW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg6AOnh8E9N0GKG14bk3ctB2WboZPxDLw',
    appId: '1:932316550763:android:9f7a3911566e1d11ee032e',
    messagingSenderId: '932316550763',
    projectId: 'barn-d496f',
    storageBucket: 'barn-d496f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCASKaSDAbOurJnlbkICZWpazMWHHqLZ00',
    appId: '1:932316550763:ios:c3904886b5cbf2f9ee032e',
    messagingSenderId: '932316550763',
    projectId: 'barn-d496f',
    storageBucket: 'barn-d496f.firebasestorage.app',
    iosBundleId: 'com.example.barnMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCASKaSDAbOurJnlbkICZWpazMWHHqLZ00',
    appId: '1:932316550763:ios:c3904886b5cbf2f9ee032e',
    messagingSenderId: '932316550763',
    projectId: 'barn-d496f',
    storageBucket: 'barn-d496f.firebasestorage.app',
    iosBundleId: 'com.example.barnMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6uCCqh2uJWIBh1m8BKsvSdvT7gyKFRqY',
    appId: '1:932316550763:web:3abc77881a78b970ee032e',
    messagingSenderId: '932316550763',
    projectId: 'barn-d496f',
    authDomain: 'barn-d496f.firebaseapp.com',
    storageBucket: 'barn-d496f.firebasestorage.app',
    measurementId: 'G-R350Y2MXK4',
  );
}
